# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# This is where you put your own keybinds. Be Mindful to check as well ~/.config/hypr/configs/Keybinds.conf to avoid conflict
# if you think I should replace the Pre-defined Keybinds in ~/.config/hypr/configs/Keybinds.conf , submit an issue or let me know in DC and present me a valid reason as to why, such as conflicting with global shortcuts, etc etc

# See https://wiki.hyprland.org/Configuring/Keywords/ for more settings and variables
# See also Laptops.conf for laptops keybinds

# /* ---- ✴️ Variables ✴️ ---- */  #
$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts
$UserConfigs = $HOME/.config/hypr/UserConfigs

#  IMPORTANT: If you want to remap and existing keybind you MUST unbindd it first

# The bindings are CASE SENSITIVE. We suggest you copy the exisitng binding here
#  Then change `bindd` to `unbind`

# E.g.
# unbind = $mainMod, Return, Open terminal, exec, $term
# bindd = $mainMod, Return, Open terminal, exec, ghostty
#
# unbind = $mainMod, E, file manager, exec, $files
# bindd = $mainMod, T, file manager, exec, $files

# If you are ADDING a bindd, make sure you include the description
# Other the keybind search menu might not show it properly

# E.g.
# bindd = $mainMod, Z, My z app, exec APPNAME

# Numpad shortcuts with NumLock off
bindd = $mainMod, KP_End, open kitty from numpad 1, exec, kitty
bindd = $mainMod, KP_Down, open zed from numpad 2, exec, zed
bindd = $mainMod, KP_Next, open zen from numpad 3, exec, /home/alborghi/.local/share/applications/downloaded/zen/zen
bindd = $mainMod, KP_Left, open thunar from numpad 4, exec, dolphin








# For passthrough keyboard into a VM
# bind = $mainMod ALT, P, submap, passthru
#submap = passthru
# to unbind
#bind = $mainMod ALT, P, submap, reset
#submap = reset

# Named workspace presets
bindd = $mainMod, F1, open work workspace preset, exec, $scriptsDir/WorkspacePreset.sh work
bindd = $mainMod, F2, open drevia workspace preset, exec, $scriptsDir/WorkspacePreset.sh drevia
bindd = $mainMod SHIFT, F1, move window to work workspace, movetoworkspace, name:work
bindd = $mainMod SHIFT, F2, move window to drevia workspace, movetoworkspace, name:drevia

# Clipboard-only area screenshot
bindd = $mainMod, X, screenshot area to clipboard, exec, $scriptsDir/ScreenShot.sh --clip-area
