---@diagnostic disable: undefined-global
---@type HL.API
local hl = hl
local ctx = rawget(_G, "ADO_HYPR") or { vars = {}, autostart = {}, loaded = {} }
_G.ADO_HYPR = ctx
local vars = ctx.vars
local function home()
  return os.getenv("HOME") or ""
end
local function require_once(module)
  if not ctx.loaded[module] then
    ctx.loaded[module] = true
    require(module)
  end
end

-- Converted from UserConfigs/UserDecorations.conf
-- /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
-- Decoration Settings
-- Hyprland Wiki Links
-- Animation - https://wiki.hyprland.org/Configuring/Animations/
-- Decoration - https://wiki.hyprland.org/Configuring/Variables/#decoration
-- Sourcing colors generated by wallust
-- source = $HOME/.config/hypr/wallust/wallust-hyprland.conf
require_once("wallust.wallust-hyprland")
hl.config({
  general = {
    border_size = 2,
    gaps_in = 0,
    gaps_out = 1,
    col = {
      active_border = (vars["color12"] or ""),
      inactive_border = (vars["color10"] or ""),
    },
}
})
-- Unconverted block line:   shadow {
hl.config({
  decoration = {
    rounding = 10,
    active_opacity = 1.0,
    inactive_opacity = 0.9,
    fullscreen_opacity = 1.0,
    dim_inactive = true,
    dim_strength = 0.1,
    dim_special = 0.8,
    shadow = {
      enabled = true,
      range = 3,
      render_power = 1,
      color = (vars["color12"] or ""),
      color_inactive = (vars["color10"] or ""),
    },
    blur = {
      enabled = true,
      size = 6,
      passes = 3,
      new_optimizations = true,
      xray = true,
      ignore_opacity = true,
      special = true,
      popups = true,
    },
}
})
-- Unconverted: }
-- Unconverted block line: 	groupbar {
hl.config({
  group = {
    groupbar = {
      col = {
        active = (vars["color0"] or ""),
      },
    },
    col = {
      border_active = (vars["color15"] or ""),
    },
}
})
-- Unconverted: }
return true
