---@diagnostic disable: undefined-global
---@type HL.API
local hl = hl
local ctx = rawget(_G, "ADO_HYPR") or { vars = {}, autostart = {}, loaded = {} }
_G.ADO_HYPR = ctx
local vars = ctx.vars
local function home()
  return os.getenv("HOME") or ""
end
local function require_once(module)
  if not ctx.loaded[module] then
    ctx.loaded[module] = true
    require(module)
  end
end

-- Converted from dms/layout.conf
-- Auto-generated by DMS - do not edit manually
hl.config({
  general = {
    gaps_in = 4,
    gaps_out = 4,
    border_size = 2,
}
})
hl.config({
  decoration = {
    rounding = 12,
}
})
return true
