---@diagnostic disable: undefined-global
---@type HL.API
local hl = hl
local ctx = rawget(_G, "ADO_HYPR") or { vars = {}, autostart = {}, loaded = {} }
_G.ADO_HYPR = ctx
local vars = ctx.vars
local function home()
  return os.getenv("HOME") or ""
end
local function require_once(module)
  if not ctx.loaded[module] then
    ctx.loaded[module] = true
    require(module)
  end
end

-- Converted from hyprlock-1080p.conf
-- /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
-- Hyprlock config for < 1080p monitor resolutions
-- Original config submitted by https://github.com/SherLock707
-- Sourcing colors generated by wallust
-- source = $HOME/.config/hypr/wallust/wallust-hyprland.conf
require_once("wallust.wallust-hyprland")
vars["Scripts"] = home() .. "/.config/hypr/scripts"
hl.config({
  general = {
    grace = 1,
    fractional_scaling = 2,
    immediate_render = true,
}
})
-- NOTE: use only 1 path
-- path = screenshot   # screenshot of your desktop
-- path = $HOME/.config/hypr/wallpaper_effects/.wallpaper_modified # by wallpaper effects
-- all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
hl.config({
  background = {
    monitor = "",
    path = home() .. "/.config/hypr/wallpaper_effects/.wallpaper_current",
    color = "rgb(0,0,0)",
    blur_size = 3,
    blur_passes = 2,
    noise = 0.0117,
    contrast = 1.3000,
    brightness = 0.8000,
    vibrancy = 0.2100,
    vibrancy_darkness = 0.0,
}
})
-- Date
hl.config({
  label = {
    monitor = "",
    text = "cmd[update:18000000] echo \"<b> \"$(date +'%A, %-d %B')\" </b>\"",
    color = (vars["color13"] or ""),
    font_size = 48,
    font_family = "Victor Mono Bold Italic",
    position = "0, -60",
    halign = "center",
    valign = "center",
}
})
-- Hour-Time
-- text = cmd[update:1000] echo "$(date +"%H")"
-- color = rgba(255, 185, 0, .8)
hl.config({
  label = {
    monitor = "",
    text = "cmd[update:1000] echo \"$(date +\"%I:%M %p\")\"",
    color = (vars["color8"] or ""),
    font_size = 130,
    font_family = "JetBrainsMono Nerd Font ExtraBold",
    position = "0, -250",
    halign = "center",
    valign = "top",
}
})
-- Minute-Time
-- label {
-- monitor =
-- text = cmd[update:1000] echo "$(date +"%M")"
-- #color = rgba(15, 10, 222, .8)
-- color = $color12
-- font_size = 150
-- font_family = JetBrainsMono Nerd Font ExtraBold
-- position = 0, -340
-- halign = center
-- valign = top
-- }
-- Seconds-Time
-- label {
-- monitor =
-- #     text = cmd[update:1000] echo "$(date +"%S")"
-- text = cmd[update:1000] echo "$(date +"%S %p")" #AM/PM
-- color = $color11
-- font_size = 32
-- font_family = JetBrainsMono Nerd Font ExtraBold
-- position = 0, -350
-- halign = center
-- valign = top
-- }
-- Put a picture of choice here. Default is the current wallpaper
-- image {
-- monitor =
-- path = $HOME/.config/hypr/wallpaper_effects/.wallpaper_current
-- size = 160
-- rounding = -1
-- border_size = 0
-- border_color = $color11
-- rotate = 0
-- reload_time = -1
-- position = 0, 280
-- halign = center
-- valign = bottom
-- Unconverted: }
-- USER
hl.config({
  label = {
    monitor = "",
    text = "  " .. (vars["USER"] or ""),
    color = (vars["color9"] or ""),
    font_size = 36,
    font_family = "Victor Mono Bold Oblique",
    position = "0, 275",
    halign = "center",
    valign = "bottom",
}
})
-- INPUT FIELD
hl.config({
  input_field = {
    monitor = "",
    size = "230, 70",
    outline_thickness = 2,
    dots_size = 0.2,
    dots_spacing = 0.2,
    dots_center = true,
    outer_color = (vars["color8"] or ""),
    inner_color = "rgba(255, 255, 255, 0.1)",
    capslock_color = "rgb(255,255,255)",
    font_color = (vars["color13"] or ""),
    fade_on_empty = false,
    font_family = "Victor Mono Bold Oblique",
    placeholder_text = "<i><span foreground=\"##ffffff99\">🔒 Type Password</span></i>",
    hide_input = false,
    position = "0, 100",
    halign = "center",
    valign = "bottom",
}
})
-- Keyboard LAYOUT
hl.config({
  label = {
    monitor = "",
    text = (vars["LAYOUT"] or ""),
    color = (vars["color8"] or ""),
    font_size = 14,
    font_family = "Victor Mono Bold Oblique",
    position = "0, 70",
    halign = "center",
    valign = "bottom",
}
})
-- uptime
hl.config({
  label = {
    monitor = "",
    text = "cmd[update:60000] echo \"<b> \"$(uptime -p || " .. (vars["Scripts"] or "") .. "/UptimeNixOS.sh)\" </b>\"",
    color = (vars["color8"] or ""),
    font_size = 24,
    font_family = "Victor Mono Bold Oblique",
    position = "0, 0",
    halign = "right",
    valign = "bottom",
}
})
-- battery information
hl.config({
  label = {
    monitor = "",
    text = "cmd[update:1000] echo \"<b> \"$(" .. (vars["Scripts"] or "") .. "/Battery.sh)\" </b>\"",
    color = (vars["color8"] or ""),
    font_size = 16,
    font_family = "Victor Mono Bold Oblique",
    position = "0, 30",
    halign = "right",
    valign = "bottom",
}
})
-- weather edit the scripts for locations
-- weather scripts are located in ~/.config/hypr/UserScripts Weather.sh and/or Weather.py
-- see https://github.com/LinuxBeginnings/Hyprland-Dots/wiki/TIPS#%EF%B8%8F-weather-app-related-for-waybar-and-hyprlock
hl.config({
  label = {
    monitor = "",
    text = "cmd[update:3600000] [ -f \"" .. home() .. "/.cache/.weather_cache\" ] && cat \"" .. home() .. "/.cache/.weather_cache\"",
    color = (vars["color8"] or ""),
    font_size = 14,
    font_family = "Victor Mono Bold Oblique",
    position = "50, 0",
    halign = "left",
    valign = "bottom",
}
})
return true
