---@diagnostic disable: undefined-global
---@type HL.API
local hl = hl
local ctx = rawget(_G, "ADO_HYPR") or { vars = {}, autostart = {}, loaded = {} }
_G.ADO_HYPR = ctx
local vars = ctx.vars
local function home()
  return os.getenv("HOME") or ""
end
local function require_once(module)
  if not ctx.loaded[module] then
    ctx.loaded[module] = true
    require(module)
  end
end

-- Converted from monitors.conf
-- Generated by nwg-displays on 2026-03-26 at 14:35:59. Do not edit manually.
hl.monitor({ output = "eDP-1", mode = "1920x1080@60.0", position = "0x0", scale = "1.0" })
hl.monitor({ output = "HDMI-A-1", mode = "3840x2160@60.0", position = "1920x0", scale = "2.0" })
return true
